version: '3.8'

services:
  backend:
    build: ./back-end
    container_name: mvp_backend
    volumes:
      - ./back-end:/app
      - ./back-end/database.db:/app/database.db
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./front-end
    container_name: mvp_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge